# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-07 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=150)),
                ('login_id', models.CharField(max_length=100)),
            ],
        ),
    ]
