# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='login_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
