# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-10 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20171008_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lname',
        ),
    ]
