# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-16 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20171011_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(default='', max_length=20)),
                ('course_name', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='courses',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.student'),
        ),
    ]
