# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-24 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0009_auto_20171016_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='all_students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(default='blank-user.jpg', upload_to=''),
        ),
    ]
