# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0012_auto_20171024_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(default='blank-user.jpg', upload_to='')),
                ('email_id', models.CharField(default='', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lname',
        ),
        migrations.AlterField(
            model_name='course',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
    ]
