# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20171024_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(default='', max_length=100)),
                ('parent_topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='proff',
            name='login_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='all_students',
            field=models.ManyToManyField(default=None, to='index.Student'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
    ]
