# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20171025_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proff',
            name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_info',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='all_students',
            field=models.ManyToManyField(default=None, to='index.Student'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
        migrations.DeleteModel(
            name='Proff',
        ),
    ]
