# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20171025_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(default='', max_length=500)),
                ('href_url', models.CharField(default='', max_length=500)),
                ('topic', models.CharField(default='', max_length=500)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('date', models.CharField(default='', max_length=100)),
                ('tag', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='all_students',
            field=models.ManyToManyField(default=None, to='index.Student'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
    ]
