# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-19 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_auto_20171118_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(default='', max_length=20)),
                ('parent_question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Question')),
                ('parent_student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='parent_student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Student'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
    ]
