# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-19 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_auto_20171119_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer_record',
            old_name='ans',
            new_name='ans_given',
        ),
        migrations.AlterField(
            model_name='answer_record',
            name='parent_student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='parent_student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Student'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
    ]
