# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-19 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_auto_20171119_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='quiz_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer_record',
            name='parent_student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='parent_student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Student'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
    ]
